#! /bin/bash

set -x
set -euo pipefail

act \
    -W .github/workflows/linux.yml \
    --container-architecture linux/"$(uname -m)" \
    --artifact-server-path="$PWD"/artifacts \
    --use-gitignore \
    "$@"
