#! /bin/bash

set -x
set -euo pipefail

arch="$(uname -m)"

act \
    -W .github/workflows/build.yml \
    --container-architecture linux/"$arch" \
    --artifact-server-path="$PWD"/artifacts \
    --use-gitignore \
    --reuse \
    "$@"
