#! /bin/bash

set -x
set -euo pipefail

swift build \
    -c release \
    -Xswiftc -static-stdlib \
    -Xlinker -lCoreFoundation \
    -Xlinker -lCFURLSessionInterface \
    -Xlinker -Bdynamic \
    -Xlinker /usr/lib/x86_64-linux-gnu/libcurl.so.4.6.0
