#! /bin/bash

set +x
set -euo pipefail

BlinkTool() {
    swift run BlinkTool "$@"
}

cat <<EOF
## Usage
\`\`\`
$(BlinkTool help)
\`\`\`

## Commands
EOF

# shellcheck disable=SC2207
commands=($(BlinkTool help | gsed -n '/^SUBCOMMANDS:/,/^$/{p;/^$/q}' | tail +2 | tail -r | tail +2 | cut -f 3 -d ' '))

for i in "${commands[@]}"; do
    cat <<EOF
### $i

\`\`\`
$(BlinkTool help "$i")
\`\`\`
EOF

done
