#! /bin/bash

BlinkTool() {
    swift run BlinkTool "$@"
}

cat <<EOF
## Usage
\`\`\`
$(BlinkTool help)
\`\`\`

## Commands
EOF

for i in $(BlinkTool help|gsed -n '/^SUBCOMMANDS:/,/^$/{p;/^$/q}'|tail +2|tail -r|tail +2|cut -f 3 -d ' '); do
    cat <<EOF
### $i

\`\`\`
$(BlinkTool help "$i")
\`\`\`
EOF

done
